//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldYachts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Message_ID { get; set; }
        public int User_ID { get; set; }
        public int Theme_ID { get; set; }
        public string Content_msg { get; set; }
        public System.DateTime DateMessage { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
